### ISSUE TITLE
Make @responsive variants possible

### ISSUE THREAD

**Issue by nilsenpaul** [benface/tailwindcss-triangles#1]
I might have overlooked this, but I don't think it's possible to do this now:

`c-triangle-up md:c-triangle-left`

Could this be made possible, by (optionally) adding responsive variants?

**Comment by benface** [comment]
With triangles being components and not utilities, normally you would do something like this to turn an "up" triangle into a "left" triangle starting from `md` screens:

```
<div class="c-triangle-up md:hidden"></div>
<div class="c-triangle-left hidden md:block"></div>
```

However, I think in this case it really makes sense to use the same element, and it was easy enough to support so I did. Update the plugin to [v2.1.0](https://github.com/benface/tailwindcss-triangles/releases/tag/v2.1.0), add `triangles: ['responsive']` to your Tailwind config's `variants` object, and you'll now be able to do this:

```
<div class="c-triangle-up md:c-triangle-left"></div>
```

Thanks for the suggestion!
